### ISSUE TITLE
Proposal: add page visibility attribute to PerformanceEventTiming entry

### ISSUE THREAD

**Issue by nhelfman** [WICG/event-timing#110] opened 2021-11-01 07:59 UTC
When processing event timing entries it can be important to determine the page visibility state the event was during its duration.
This is important since events which occurred (or completed) while the page was not visible may have longer duration due to UA CPU throttling. 

Without being able to distinguish between the entries based on page visibility it is hard to collect reliable information about the responsiveness performance.

The is no simple way to exclude these events. Using Page Visibility API to determine that can be fragile and inaccurate.

**Comment by npm1** [comment] 2021-12-23 17:49
Is this a dupe of https://github.com/w3c/performance-timeline/issues/105? Let me know if we can close this in favor of that.

**Comment by nhelfman** [comment] 2021-12-26 09:20
Sure. Assuming the performance timeline issue will be resolved in a way which provides reliable way to determine the visibility (or even better "throttled state") during the event period.

**Comment by npm1** [comment] 2022-01-10 14:15
Specifically when would you consider an event to be affected by visibility? Note that there may be changes in visibility from the time the event occurs to the end time of the Event Timing `duration` attribute.

**Comment by npm1** [comment] 2022-01-27 20:37
Anyways, let's keep the discussion on the Performance Timeline issue I linked above.

**Closed by npm1** 2022-01-27 20:37 UTC
